CREATE TABLE TRAINER (
	trainer_id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	-- gym_id TEXT NOT NULL,
	sponsor TEXT NOT NULL,
	-- FOREIGN KEY (gym_id) REFERENCES GYM,
	FOREIGN KEY (sponsor) REFERENCES SPONSOR
);
